CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL
)

CREATE TABLE IF NOT EXISTS urls (
    id SERIAL PRIMARY KEY NOT NULL,
    short_url TEXT UNIQUE NOT NULL,
    redirect_url TEXT NOT NULL,
    user_id SERIAL REFERENCES users(id) ON DELETE CASCADE
)